version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'flask run --host=0.0.0.0'
        ports:
            - 80:5000
        volumes: 
            - .:/app
        depends_on:
            - db
    db:
        image: mysql:5.7.22
        restart: always
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 33067:3306
